services:
  gedi:
    image: gedi
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - "../:/gedi:rw"
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISPLAY
      - TERM
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    privileged: true
    stdin_open: true
    tty: true